name: Daily DB Backup
on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:      # Allows manual triggers

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install PyGithub sqlite3
      - run: python backup.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
